spring.application.name=Forvity

app.bootstrap.admin.email=
app.bootstrap.admin.password=

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
